---
title: "Financial data analysis"
format: html
editor: visual 
---

```{r}
#| message: false 
here::i_am("dplyr-102.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)

```

## Data LOADING 
```{r}
#| message: false 
clients<- vroom (here("data","client.csv"))
accounts<- vroom (here("data","account.csv"))
disp<- vroom (here("data","disp.csv"))
```

## Joining data tables 
A collection of joining functions of the form `*_join`

## Iner join
```{r}
da <-inner_join(accounts,disp) #over column that have same names 
```
```{r}
cda <-inner_join(clients, da, by=join_by(client_id), suffix= c("_home","_bank"))
```

```{r}
home_diff_bank <- cda |> filter(district_id_home != district_id_bank) |> nrow() #filter operates at the level of a single row so if need to compare multiple rows use group by 
```

We observe that `r home_diff_bank` clients have a bank in another district as the one they live in

```{r}
cda |> group_by(account_id) |>
  distinct(district_id_home) |> 
  summarise(N=n()) |> 
  filter(N>1)


```
```{r}
clients|> 
  ggplot(aes(y=gender)) + geom_bar()
```

### Gender Gap

```{r}
clients|> count(gender)
```
```{r}
clients|> 
  ggplot(aes(x=gender)) + geom_bar() + coord_flip()
```
```{r}
cda|>
count(gender, type)|>
  group_by(gender)|>
  mutate(freq=n /sum(n))|>
  select(-n)|>
  ungroup()|>
  pivot_wider(values_from = freq, names_from = type)
```

```{r}
cda|> 
  ggplot(aes(y=gender,fill=type)) + geom_bar(position="fill")
```
```{r}
chisq.test(cda|> pull(gender),
           cda|> pull(type))
```

